-- AI Improvement Proposals — stores suggested changes to the AI agent
-- Generated by weekly analysis of low-scoring conversations
-- Admin reviews and accepts/rejects each proposal

CREATE TABLE IF NOT EXISTS ai_improvements (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- What to change
  category TEXT NOT NULL CHECK (category IN ('prompt_rule', 'tone', 'objection_handling', 'qualification', 'campaign_context', 'compliance', 'escalation', 'general')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,

  -- The proposed change
  current_behavior TEXT,          -- what the AI does now
  proposed_behavior TEXT NOT NULL, -- what it should do instead
  evidence TEXT[],                -- conversation excerpts that triggered this
  affected_rule TEXT,             -- which RULE # or section of prompt this modifies

  -- Scoring context
  avg_score_before NUMERIC(3,1), -- avg audit score for convos with this issue
  conversations_affected INTEGER DEFAULT 0,

  -- Review status
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'implemented')),
  reviewed_at TIMESTAMPTZ,
  reviewed_by TEXT,               -- 'karim' or 'auto'
  rejection_reason TEXT,

  -- If accepted, what changed
  implementation_note TEXT,

  -- Priority
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),

  -- Metadata
  source TEXT DEFAULT 'weekly_audit', -- 'weekly_audit', 'manual', 'campaign_test'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for pending review queue
CREATE INDEX IF NOT EXISTS idx_ai_improvements_status ON ai_improvements(status, priority);

-- Auto-update timestamp
CREATE OR REPLACE TRIGGER set_ai_improvements_updated_at
  BEFORE UPDATE ON ai_improvements
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Service role access (admin only)
ALTER TABLE ai_improvements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to ai_improvements"
  ON ai_improvements
  FOR ALL
  USING (auth.role() = 'service_role');
