-- System alerts — auto-generated by /api/cron/check-alerts
CREATE TABLE IF NOT EXISTS system_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_key TEXT UNIQUE NOT NULL,          -- dedupe key e.g. 'db_latency', 'lead_count'
  category TEXT NOT NULL DEFAULT 'engineering', -- engineering, finance, legal
  severity TEXT NOT NULL DEFAULT 'info',    -- info, warning, critical
  title TEXT NOT NULL,
  message TEXT,
  metric_value TEXT,                        -- current measured value
  threshold TEXT,                           -- threshold that triggered
  resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: only service role writes, admin reads via API
ALTER TABLE system_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access" ON system_alerts
  FOR ALL USING (true) WITH CHECK (true);
